version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious
    restart: unless-stopped
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          host: invidious-db
          port: 5432
        check_tables: true
        hmac_key: ${HMAC_KEY}
        domain: ${DOMAIN}
        https_only: false
        hsts: true
        external_port: ${EXTERNAL_PORT:-443}
        use_pubsub_feeds: true
        use_innertube_for_captions: true
        statistics_enabled: true
        pool_size: 200
        registration_enabled: ${REGISTRATION_ENABLED:-true}
        login_enabled: ${LOGIN_ENABLED:-true}
        captcha_enabled: ${CAPTCHA_ENABLED:-true}
        po_token: ${PO_TOKEN}
        visitor_data: ${VISITOR_DATA}
        signature_server: inv_sig_helper:${SIG_HELPER_PORT:-12999}
        popular_enabled: true
        enable_user_notifications: true
        cache_annotations: true
        playlist_length_limit: 1000
        default_user_preferences:
          locale: ${DEFAULT_LOCALE:-"en-US"}
          region: ${DEFAULT_REGION:-"US"}
          dark_mode: "dark"
          thin_mode: false
          feed_menu: ["Home"]
          default_home: "Popular"
          max_results: 60
          quality: "dash"
          quality_dash: "best"
          volume: 100
          player_style: "youtube"
          extend_desc: true
          related_videos: false
          show_nick: true
          comments: ["youtube", "reddit"]
          captions: ["English", "", ""]
          annotations: false
          annotations_subscribed: false
          preload: true
          autoplay: true
          continue: true
          continue_autoplay: true
          listen: false
          video_loop: false
          save_player_pos: true
          speed: 1.0
          vr_mode: true
          local: false
        channel_threads: 4
        feed_threads: 4
        channel_refresh_interval: 30m
        full_refresh: false
        jobs:
          clear_expired_items:
            enable: true
          refresh_channels:
            enable: true
          refresh_feeds:
            enable: true
        banner: |
          <style>
            /* Remove footer */
            footer { display: none !important; }

            /* Dark theme improvements */
            body.dark-theme {
              background-color: #000000 !important;
              color: #ffffff !important;
            }
            .dark-theme .pure-menu {
              background-color: #000000 !important;
            }
            .dark-theme .pure-menu-link:hover {
              background-color: #1a1a1a !important;
            }
            .dark-theme input, 
            .dark-theme select, 
            .dark-theme textarea {
              background-color: #111111 !important;
              border: 1px solid #333333 !important;
              color: #ffffff !important;
            }
            .dark-theme .pure-form legend {
              color: #ffffff !important;
            }
            .dark-theme .pure-button-primary {
              background-color: #1a73e8 !important;
            }
            .dark-theme .pure-button {
              background-color: #333333 !important;
              color: #ffffff !important;
            }

            /* Player customization */
            .vjs-menu-item.vjs-selected,
            .vjs-menu-item:focus,
            .vjs-menu-item:hover,
            .vjs-progress-holder .vjs-play-progress,
            .vjs-slider-bar.vjs-play-progress,
            .vjs-volume-level,
            .vjs-play-progress,
            .vjs-volume-level,
            .vjs-loading-spinner {
              background-color: #f1f1f1 !important;
            }
            .vjs-menu-button-popup .vjs-menu {
              background-color: rgba(0, 0, 0, 0.9) !important;
            }
            /* Hide share button */
            .vjs-share-control {
              display: none !important;
            }
            /* Remove cyan from all player elements */
            .vjs-time-tooltip,
            .vjs-play-progress:before,
            .vjs-slider-handle,
            .vjs-volume-level:before,
            .vjs-text-track-display,
            .vjs-loading-spinner:before,
            .vjs-loading-spinner:after,
            .vjs-control:focus,
            .vjs-button:hover,
            .vjs-menu-button-popup:hover,
            .cc-button,
            .video-js .vjs-control:focus,
            .video-js .vjs-big-play-button:focus {
              color: #f1f1f1 !important;
              border-color: #f1f1f1 !important;
              text-shadow: none !important;
              box-shadow: none !important;
              background-color: rgba(255, 255, 255, 0.1) !important;
            }

            /* Hide trending-related elements */
            a[href="/feed/trending"],
            .trending-section,
            .pure-menu-item a[href="/feed/trending"] {
              display: none !important;
            }

            /* Rename "Popular" to "Home" in UI */
            a[href="/feed/popular"]:before {
              content: 'Home';
              visibility: visible;
              position: absolute;
            }
            a[href="/feed/popular"] {
              visibility: hidden;
            }

            /* Video.js player customization */
            /* Base player */
            .video-js {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, sans-serif !important;
            }
            
            /* All VideoJS elements */
            .video-js .vjs-control,
            .video-js .vjs-big-play-button,
            .video-js .vjs-time-tooltip,
            .video-js .vjs-mouse-display,
            .video-js .vjs-volume-tooltip {
              background-color: rgba(0, 0, 0, 0.6) !important;
              color: #ffffff !important;
              text-shadow: none !important;
            }

            /* Progress bar and volume */
            .video-js .vjs-load-progress,
            .video-js .vjs-load-progress div {
              background: rgba(255, 255, 255, 0.3) !important;
            }

            /* Big play button */
            .video-js .vjs-big-play-button {
              border-color: #ffffff !important;
              background-color: rgba(0, 0, 0, 0.6) !important;
            }
          </style>
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db
      - inv_sig_helper

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:${SIG_HELPER_PORT:-12999}"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 12999 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql:ro
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

volumes:
  postgresdata:
